services:
  identity-db:
    image: postgres:17
    container_name: budget_identity_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=identity_db
      - POSTGRES_USER=admin_identity_db
      - POSTGRES_PASSWORD=pass_identity_db
    ports:
      - "5432:5432"
    volumes:
      - identity_db_data:/var/lib/postgres/data

volumes:
    identity_db_data:
    